### ISSUE TITLE
When will the videos be available?

### ISSUE THREAD

**Issue by yubeiluo** [wmcnally/golfdb#1]
I am reading your paper entitled "GolfDB: A Video Database for Golf Swing Sequencing" saying that there will be a curated list of high quality golf sequencing videos for benchmarks. So when will the videos be available?

**Comment by wmcnally** [comment]
The video urls are available in the dataset file. I will not be uploading the videos, as I do not own them. You must download them yourself. I apologize for the inconvenience. I will upload code to preprocess the videos.

**Comment by wmcnally** [comment]
@yubeiluo I have provided a link to the preprocessed videos for a frame size of 160x160 and some starter PyTorch code to go along with it. Please let me know if there are any issues.
