### ISSUE TITLE
Hey i am not able to get the coordinates of golf face even from test_video.py. Can you please tell me how do i get coordinates and not just frames where golf face is detected?

### ISSUE THREAD

**Issue by onkar-99** [wmcnally/golfdb#11]
Hey i am not able to get the coordinates of golf face even from test_video.py. Can you please tell me how do i get coordinates and not just frames where golf face is detected?

_Originally posted by @onkar-99 in https://github.com/wmcnally/golfdb/issues/5#issuecomment-877594570_

**Comment by wmcnally** [comment]
@onkar-99 I’m not sure what you mean when you say “coordinates of golf face.” SwingNet only outputs the swing event probabilities.

**Comment by onkar-99** [comment]
So I won't be able to get the coordinates of the face part of golf stick? I thought it does object detection because i wanted to trace golf swing path in a video for which i had to find the coordinates of the face part of golf stick in each frame.

**Comment by wmcnally** [comment]
No, SwingNet does not provide the coordinates of the clubface. It does not do object detection, only event detection.
