### ISSUE TITLE
What is the sequence length here?

### ISSUE THREAD

**Issue by Imen29** [wmcnally/golfdb#12]
Hello!
I want to know what is the seq_lenghth in train.py and eval.py? 
thanks a lot!

**Comment by wmcnally** [comment]
64

**Comment by Imen29** [comment]
not a value of seq_length i am asking about its description ??!! 
thanks.

**Comment by Imen29** [comment]
@wmcnally, not a value of seq_length i am asking about its description ??!!
thanks in advance.

**Comment by wmcnally** [comment]
It's the number of frames in the input. The input to the model has 5 dimensions: (batch, frames, height, width, channels). So with a batch size of 1, sequence length of 64, and image size of 160x160, the input would have the shape (1, 64, 160, 160, 3). Hope this helps.

**Comment by Imen29** [comment]
@wmcnally  thanks
