### ISSUE TITLE
May I request the unprocessed video clips?

### ISSUE THREAD

**Issue by Zachs-Playground** [wmcnally/golfdb#16]
Hi Will,

Thank you so much for making your dataset and code publicly available. May I ask you for the unprocessed video clips? The reason I am asking this is that I am trying to learn the texture and normal map for golf players from the videos. My project will be based on your high-resolution video set. Thank you again for your help.

Zach

**Comment by wmcnally** [comment]
The YouTube url ids are given in the dataset

**Comment by Zachs-Playground** [comment]
Found it. Thank you for the reply.
