### ISSUE TITLE
how to test another videos?

### ISSUE THREAD

**Issue by chanho31** [wmcnally/golfdb#3]
I want to play eval.py with my golf video.
But I can't figure out how to make a mat file like golfdb so it's impossible to test it with my golf video.
I tried to use preprocess_videos.py but it failed.
Can you teach me one example of preprocess_videos.py and mat files?

**Comment by wmcnally** [comment]
You do not need to make a mat file to test your own video. You should be able to modify preprocess_videos.py to prepare your own video, then you can process it using the pretrained model by modifying the eval.py code.

**Comment by wmcnally** [comment]
See newly added test_video.py for processing your own videos. Hope this helps.
