### ISSUE TITLE
Modifying eval.py

### ISSUE THREAD

**Issue by liamhunn27** [wmcnally/golfdb#5]
Hi,

I want to use this model to return the location of the swing events for an individual video or even better, an image of each of the events. How should I modify eval.py to do this? 

I also don't have access to a computer with a GPU at the moment because of Covid-19, so is it possible to do this without CUDA? 

Kind regards,
Liam

**Comment by wmcnally** [comment]
Hi Liam. See newly added test_video.py for processing your own videos. Hope this helps.

**Comment by onkar-99** [comment]
Hey i am not able to get the coordinates of golf face even from test_video.py. Can you please tell me how do i get coordinates and not just frames where golf face is detected?

**Comment by wmcnally** [comment]
@onkar-99 I’m not sure what you mean when you say “coordinates of golf face.” SwingNet only outputs the swing event probabilities.
