### ISSUE TITLE
Original full resolution videos

### ISSUE THREAD

**Issue by Favoreel** [wmcnally/golfdb#7]
Hi,

Are the original full resolution videos available for download (instead of the 160x160 downscaled)?

Thx!

Wouter

**Comment by wmcnally** [comment]
Not directly. Our dataset provides the YouTube URLs.

**Comment by marcm07** [comment]
Hi, where do we find the dataset with the URLs?

**Comment by wmcnally** [comment]
Run generate_splits.py to generate .pkl files containing the dataframes. Load the pkl dataframes using pandas. The youtube ids are under the column 'youtube_id'. The corresponding url is given by https://www.youtube.com/watch?v=[youtube_id]
