### ISSUE TITLE
Pytorch 1.3 version does not exist on the official website

### ISSUE THREAD

**Issue by Eimuy** [wmcnally/golfdb#8]
Hello, 
There is a problem with the installation of pytorch, so I want to execute pip install pytorch==1.3 alone, but the system prompts no Found that pytorch==1.3, and then I checked on the pytorch official website, I did not find pytorch 1.3 version, so I want to confirm whether there is a version error in the environment you provide?

**Comment by wmcnally** [comment]
@Eimuy the code should still work with newer versions of PyTorch. Please try with a newer version.

**Comment by Eimuy** [comment]
thank you @wmcnally
