### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Eimuy** [wmcnally/golfdb#9]
/content/drive/MyDrive/golfdb_master# python test_video.py -p content/drive/MyDrive/golfdb_master/test_video.mp4
Preparing video: content/drive/MyDrive/golfdb_master/test_video.mp4
Using device: cuda
Loaded model weights
Testing...
Traceback (most recent call last):
  File "test_video.py", line 95, in <module>
    for sample in dl:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "test_video.py", line 35, in __getitem__
    ratio = self.input_size / max(frame_size)
ZeroDivisionError: float division by zero

Hello,
Everything works fine,, but when i aml trying to run "python test_video.p -p test_video.mp4 ",, i have this message in below: zeroDevisionError..
Did you happen to solve the problem for yourself? What did it end up being?

**Comment by wmcnally** [comment]
Did it find the video correctly? Is test_video.mp4 in the main folder?

**Comment by Eimuy** [comment]
@wmcnally yes.. i tried to run this command " python test_video.py -p content/drive/MyDrive/golfdb_master/test_video.mp4" and i added the video path in the command " content/drive/MyDrive/golfdb_master/test_video.mp4.

**Comment by HadhamiRjiba** [comment]
it still showing the same error : " zeroDevisionError."

**Comment by wmcnally** [comment]
If that is an absolute path, it should start with '/'... e.g., /content/drive/MyDrive/golfdb_master/test_video.mp4

**Comment by HadhamiRjiba** [comment]
it work but now i have this message in blow:

Preparing video: /content/drive/MyDrive/golfdb_master/test.mp4
Using device: cuda
Loaded model weights
Testing...
Predicted event frames: [ 447   15   18   24   29 2368   30   48]
Condifence: [0.161, 0.363, 0.378, 0.616, 0.649, 0.368, 0.353, 0.393]
**: cannot connect to X server**

**Comment by Eimuy** [comment]
it works but now i have this message in blow:

Preparing video: /content/drive/MyDrive/golfdb_master/test.mp4
Using device: cuda
Loaded model weights
Testing...
Predicted event frames: [ 447 15 18 24 29 2368 30 48]
Condifence: [0.161, 0.363, 0.378, 0.616, 0.649, 0.368, 0.353, 0.393]
**: cannot connect to X server**

**Comment by HadhamiRjiba** [comment]
**": cannot connect to X server"**

**Comment by wmcnally** [comment]
I have not seen this error before. Are you running the code on a server?

**Comment by Eimuy** [comment]
i am running the code on google colab (vs code(code server)) by this line: **ColabCode (port=30002, password="eimuy")**
so maybe i should change the port number?!!

**Comment by wmcnally** [comment]
https://stackoverflow.com/questions/55288657/image-is-not-displaying-in-google-colab-while-using-imshow
